import Head from 'next/head'

export default function Home() {
  return (
    < >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <h1 className='font-bold text-5xl '>hello</h1>
      
    </>
  )
}
